Update action.yml to match spec
Reggionick/s3-deploy pull request #10
Opened 2020-09-29 02:23 UTC by mileszim

It looks like the spec in action.yml was missing the changes from v1 -> v2. This PR Updates that.

Here's the error when action runs right now
<img width="1102" alt="Screen Shot 2020-09-28 at 7 23 00 PM" src="https://user-images.githubusercontent.com/1849508/94505496-0f7b0080-01c0-11eb-9420-5f82b6726513.png">

2020-09-29 10:13 UTC, Reggionick requested changes
Thanks for the PR!

2020-09-29 10:13 UTC, Reggionick commented on action.yml
> +    description: 'Removes files in S3, that are not available in the local copy of the directory'
Could you please remove the comma?

2020-09-29 20:43 UTC, mileszim commented on action.yml
> +    description: 'Removes files in S3, that are not available in the local copy of the directory'
for sure!

2020-09-30 07:21 UTC, Reggionick approved these changes

2020-09-30 07:21 UTC, merged